# https://goframe.org/docs/web/server-config-file-template
server:
  address: ":8000"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"

# https://goframe.org/docs/core/glog-config
logger:
  level: "all"
  stdout: true

chat_model:
  api_key: ""
  base_url: "https://api.deepseek.com"
  model: "deepseek-v4-pro"

chat_model_fast:
  api_key: ""
  base_url: "https://api.deepseek.com"
  model: "deepseek-v4-flash"

embedding_model:
  api_key: ""
  base_url: "https://ark.cn-beijing.volces.com/api/v3"
  model: "doubao-embedding-text-240515"
  dimension: 1024

file_dir: "/你的路径/SuperBizAgent/internal/ai/cmd/knowledge_cmd/docs"

milvus:
  address: "localhost:19530"

log_topic:
  region: ""
  id: ""

mcp:
  log_url: ""

mysql:
  dsn: ""
