// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package chat

import (
	"SuperBizAgent/api/chat"
	"SuperBizAgent/internal/ai/analytics"
	"SuperBizAgent/internal/ai/chatops"
	"SuperBizAgent/internal/ai/collaboration"
	"SuperBizAgent/internal/ai/feedback"
	"SuperBizAgent/internal/app"
	"SuperBizAgent/internal/logic/sse"
)

type ControllerV1 struct {
	service            *sse.Service
	chatApp            *app.ChatApp
	knowledgeApp       *app.KnowledgeApp
	aiopsApp           *app.AIOpsApp
	changeEventApp     *app.ChangeEventApp
	mcpToolApp         *app.MCPToolApp
	userSkillApp       *app.UserSkillApp
	cmdbApp            *app.CMDBApp
	feedbackStore      *feedback.Store
	analyticsCollector *analytics.Collector
	shareStore         *collaboration.ShareStore
	feishuSender       *chatops.FeishuSender
}

func NewV1(chatApp *app.ChatApp, knowledgeApp *app.KnowledgeApp, aiopsApp *app.AIOpsApp,
	changeEventApp *app.ChangeEventApp,
	mcpToolApp *app.MCPToolApp, userSkillApp *app.UserSkillApp, cmdbApp *app.CMDBApp,
	feedbackStore *feedback.Store, analyticsCollector *analytics.Collector,
	shareStore *collaboration.ShareStore, feishuSender *chatops.FeishuSender) chat.IChatV1 {
	return &ControllerV1{
		service:            sse.New(),
		chatApp:            chatApp,
		knowledgeApp:       knowledgeApp,
		aiopsApp:           aiopsApp,
		changeEventApp:     changeEventApp,
		mcpToolApp:         mcpToolApp,
		userSkillApp:       userSkillApp,
		cmdbApp:            cmdbApp,
		feedbackStore:      feedbackStore,
		analyticsCollector: analyticsCollector,
		shareStore:         shareStore,
		feishuSender:       feishuSender,
	}
}
