// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package chat

import (
	"SuperBizAgent/api/chat"
	"SuperBizAgent/internal/app"
	"SuperBizAgent/internal/logic/sse"
)

type ControllerV1 struct {
	service      *sse.Service
	chatApp      *app.ChatApp
	knowledgeApp *app.KnowledgeApp
	aiopsApp     *app.AIOpsApp
}

func NewV1(chatApp *app.ChatApp, knowledgeApp *app.KnowledgeApp, aiopsApp *app.AIOpsApp) chat.IChatV1 {
	return &ControllerV1{
		service:      sse.New(),
		chatApp:      chatApp,
		knowledgeApp: knowledgeApp,
		aiopsApp:     aiopsApp,
	}
}
