server:
  address: ":8000"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"

logger:
  level: "all"
  stdout: true

# AI 模型配置 (后续我们将在这里填入具体的 Key)
ds_think_chat_model:
  api_key: "sk-6ef26a51b4f94a4c9fe057a9efa81e8e"
  base_url: "https://api.deepseek.com"
  model: "deepseek-chat"

# 知识库文件存储路径 (请修改为你本地的实际路径)
file_dir: "E:/knowledge base"
